Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    VPC:
        Description: The VPC to deploy the security groups to
        Type: 'AWS::EC2::VPC::Id'
    SourceCidr:
        Description: The source CidrIp to allow access to The Hive from.
        Type: String
Resources:
    ECSHostSecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            VpcId:
                Ref: VPC
            GroupDescription: Allow access The Hives ECS hosts
            SecurityGroupIngress:
                -
                    SourceSecurityGroupId:
                        Ref: LoadBalancerSecurityGroup
                    IpProtocol: -1
            Tags:
                -
                    Key: Name
                    Value:
                        'Fn::Sub': '${EnvironmentName}-ECS-Hosts'
    LoadBalancerSecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            VpcId:
                Ref: VPC
            GroupDescription: The Hives ALB security group
            SecurityGroupIngress:
                -
                    CidrIp:
                        Ref: SourceCidr
                    FromPort: 443
                    ToPort: 443
                    IpProtocol: tcp
            Tags:
                -
                    Key: Name
                    Value:
                        'Fn::Sub': '${EnvironmentName}-LoadBalancers'
Outputs:
    ECSHostSecurityGroup:
        Description: A reference to the security group for ECS hosts
        Value:
            Ref: ECSHostSecurityGroup
    LoadBalancerSecurityGroup:
        Description: A reference to the security group for load balancers
        Value:
            Ref: LoadBalancerSecurityGroup
