Description: >

    This template deploys an ECS cluster and task definitions for running
    Elasticsearch, Cortex and The Hive security case management tooling.

    Last Modified: 2 April 2018 
    Author: Glenn Bolton
Parameters:
    InstanceType:
        Description: Select the instance type for the ECS cluster nodes.
        Type: String
        Default: t2.micro
        AllowedValues:
            - t2.micro
            - t2.small
            - t2.medium
            - t2.large
            - t2.xlarge
            - m5.large
    ClusterSize:
        Description: Enter the ECS cluster node count.
        Type: Number
        Default: 2
    VPC:
        Description: Select the VPC to deploy the ECS cluster to.
        Type: 'AWS::EC2::VPC::Id'
    Subnets:
        Description: Select the VPC subnets to deploy the ECS cluster in.
        Type: 'List<AWS::EC2::Subnet::Id>'
    SourceCidr:
        Description: The source CidrIp to allow access to The Hive from.
        Default: 10.0.0.0/8
        Type: String
    CodeBucket:
        Description: >-
            The name of the S3 bucket which contains the CloudFormation
            templates.
        Type: String
Resources:
    SecurityGroups:
        Type: 'AWS::CloudFormation::Stack'
        Properties:
            TemplateURL:
                Fn::Join:
                    - ''
                    -
                        - 'https://s3.amazonaws.com/'
                        -
                            Ref: CodeBucket
                        - /infra-security-groups.yaml
            Parameters:
                EnvironmentName:
                    Ref: 'AWS::StackName'
                VPC:
                    Ref: VPC
                SourceCidr:
                    Ref: SourceCidr
    ALB:
        Type: 'AWS::CloudFormation::Stack'
        Properties:
            TemplateURL:
                Fn::Join:
                    - ''
                    -
                        - 'https://s3.amazonaws.com/'
                        -
                            Ref: CodeBucket
                        - /infra-load-balancers.yaml
            Parameters:
                EnvironmentName:
                    Ref: 'AWS::StackName'
                VPC:
                    Ref: VPC
                Subnets:
                    Ref: Subnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup
    ECS:
        Type: 'AWS::CloudFormation::Stack'
        Properties:
            TemplateURL:
                Fn::Join:
                    - ''
                    -
                        - 'https://s3.amazonaws.com/'
                        -
                            Ref: CodeBucket
                        - '/infra-ecs-cluster.yaml'
            Parameters:
                EnvironmentName:
                    Ref: 'AWS::StackName'
                InstanceType:
                    Ref: InstanceType
                ClusterSize:
                    Ref: ClusterSize
                VPC:
                    Ref: VPC
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                Subnets:
                    Ref: Subnets
